@startuml

Cuestionario -->"*" Pregunta
Encuestado --> Cuestionario
Encuestado -->"*" Respuesta
Respuesta --> Pregunta 

class Cuestionario {

}

class Respuesta {
    Pregunta
    valorRespondido
}

@enduml